# Generated by Django 5.1.7 on 2025-03-09 14:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000, unique=True)),
                ('article_count', models.PositiveIntegerField(default=0)),
                ('total_claps', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['-article_count'],
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000)),
                ('_claps_str', models.CharField(db_column='claps', max_length=100)),
                ('reading_time', models.IntegerField()),
                ('link', models.URLField(max_length=2000)),
                ('text', models.TextField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='articles.author')),
            ],
            options={
                'ordering': ['-reading_time'],
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('article_count', models.PositiveIntegerField(default=0)),
                ('articles', models.ManyToManyField(related_name='topics', to='articles.article')),
            ],
            options={
                'ordering': ['-article_count'],
            },
        ),
    ]
